//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Text.Json;



namespace cfg
{

public sealed partial class StartMachineConfig :  Bright.Config.BeanBase 
{
    public StartMachineConfig(JsonElement _json) 
    {
        Id = _json.GetProperty("Id").GetInt32();
        InnerIP = _json.GetProperty("InnerIP").GetString();
        OuterIP = _json.GetProperty("OuterIP").GetString();
        WatcherPort = _json.GetProperty("WatcherPort").GetString();
        PostInit();
    }

    public StartMachineConfig(int Id, string InnerIP, string OuterIP, string WatcherPort ) 
    {
        this.Id = Id;
        this.InnerIP = InnerIP;
        this.OuterIP = OuterIP;
        this.WatcherPort = WatcherPort;
        PostInit();
    }

    public static StartMachineConfig DeserializeStartMachineConfig(JsonElement _json)
    {
        return new StartMachineConfig(_json);
    }

    public int Id { get; private set; }
    /// <summary>
    /// 内网地址
    /// </summary>
    public string InnerIP { get; private set; }
    /// <summary>
    /// 外网地址
    /// </summary>
    public string OuterIP { get; private set; }
    /// <summary>
    /// 守护进程端口
    /// </summary>
    public string WatcherPort { get; private set; }

    public const int __ID__ = 1628109127;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "InnerIP:" + InnerIP + ","
        + "OuterIP:" + OuterIP + ","
        + "WatcherPort:" + WatcherPort + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}
