//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Text.Json;



namespace cfg
{

public sealed partial class StartSceneConfig :  Bright.Config.BeanBase 
{
    public StartSceneConfig(JsonElement _json) 
    {
        Id = _json.GetProperty("Id").GetInt32();
        Process = _json.GetProperty("Process").GetInt32();
        Zone = _json.GetProperty("Zone").GetInt32();
        SceneType = (Enum.SceneType)_json.GetProperty("SceneType").GetInt32();
        Name = _json.GetProperty("Name").GetString();
        OuterPort = _json.GetProperty("OuterPort").GetInt32();
        PostInit();
    }

    public StartSceneConfig(int Id, int Process, int Zone, Enum.SceneType SceneType, string Name, int OuterPort ) 
    {
        this.Id = Id;
        this.Process = Process;
        this.Zone = Zone;
        this.SceneType = SceneType;
        this.Name = Name;
        this.OuterPort = OuterPort;
        PostInit();
    }

    public static StartSceneConfig DeserializeStartSceneConfig(JsonElement _json)
    {
        return new StartSceneConfig(_json);
    }

    public int Id { get; private set; }
    /// <summary>
    /// 所属进程
    /// </summary>
    public int Process { get; private set; }
    /// <summary>
    /// 所属区
    /// </summary>
    public int Zone { get; private set; }
    /// <summary>
    /// 类型
    /// </summary>
    public Enum.SceneType SceneType { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 外网端口
    /// </summary>
    public int OuterPort { get; private set; }

    public const int __ID__ = 1499456844;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Process:" + Process + ","
        + "Zone:" + Zone + ","
        + "SceneType:" + SceneType + ","
        + "Name:" + Name + ","
        + "OuterPort:" + OuterPort + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}
