//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Text.Json;



namespace cfg
{

public sealed partial class StartProcessConfig :  Bright.Config.BeanBase 
{
    public StartProcessConfig(JsonElement _json) 
    {
        Id = _json.GetProperty("Id").GetInt32();
        MachineId = _json.GetProperty("MachineId").GetInt32();
        InnerPort = _json.GetProperty("InnerPort").GetInt32();
        AppName = _json.GetProperty("AppName").GetString();
        PostInit();
    }

    public StartProcessConfig(int Id, int MachineId, int InnerPort, string AppName ) 
    {
        this.Id = Id;
        this.MachineId = MachineId;
        this.InnerPort = InnerPort;
        this.AppName = AppName;
        PostInit();
    }

    public static StartProcessConfig DeserializeStartProcessConfig(JsonElement _json)
    {
        return new StartProcessConfig(_json);
    }

    public int Id { get; private set; }
    /// <summary>
    /// 所属机器
    /// </summary>
    public int MachineId { get; private set; }
    /// <summary>
    /// 内网端口
    /// </summary>
    public int InnerPort { get; private set; }
    /// <summary>
    /// 程序名
    /// </summary>
    public string AppName { get; private set; }

    public const int __ID__ = 2140444015;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "MachineId:" + MachineId + ","
        + "InnerPort:" + InnerPort + ","
        + "AppName:" + AppName + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}
