//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Text.Json;



namespace cfg
{

public sealed partial class StartZoneConfig :  Bright.Config.BeanBase 
{
    public StartZoneConfig(JsonElement _json) 
    {
        Id = _json.GetProperty("Id").GetInt32();
        DBConnection = _json.GetProperty("DBConnection").GetString();
        DBName = _json.GetProperty("DBName").GetString();
        PostInit();
    }

    public StartZoneConfig(int Id, string DBConnection, string DBName ) 
    {
        this.Id = Id;
        this.DBConnection = DBConnection;
        this.DBName = DBName;
        PostInit();
    }

    public static StartZoneConfig DeserializeStartZoneConfig(JsonElement _json)
    {
        return new StartZoneConfig(_json);
    }

    public int Id { get; private set; }
    /// <summary>
    /// 数据库地址
    /// </summary>
    public string DBConnection { get; private set; }
    /// <summary>
    /// 数据库名
    /// </summary>
    public string DBName { get; private set; }

    public const int __ID__ = -457316368;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "DBConnection:" + DBConnection + ","
        + "DBName:" + DBName + ","
        + "}";
    }

    partial void PostInit();
    partial void PostResolve();
}
}
