//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Text.Json;



namespace cfg
{


public sealed partial class StartProcessTable
{
    private readonly Dictionary<int, StartProcessConfig> _dataMap;
    private readonly List<StartProcessConfig> _dataList;
    
    public StartProcessTable(JsonElement _json)
    {
        _dataMap = new Dictionary<int, StartProcessConfig>();
        _dataList = new List<StartProcessConfig>();
        
        foreach(JsonElement _row in _json.EnumerateArray())
        {
            var _v = StartProcessConfig.DeserializeStartProcessConfig(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, StartProcessConfig> DataMap => _dataMap;
    public List<StartProcessConfig> DataList => _dataList;

    public StartProcessConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StartProcessConfig Get(int key) => _dataMap[key];
    public StartProcessConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    

    partial void PostInit();
    partial void PostResolve();
}

}