using System.IO;
using System.Text;
using ET.UIFlow;
using UnityEditor;
using UnityEngine;

[CustomEditor(typeof(UIBindComponent))]
public class UIComponentEditor : Editor
{
    private SerializedProperty uiName;
    private SerializedProperty uiData;
    private void OnEnable()
    {
        uiName = serializedObject.FindProperty(nameof(UIBindComponent.uiName));
        uiData = serializedObject.FindProperty(nameof(UIBindComponent.uiData));

        if (string.IsNullOrEmpty(uiName.stringValue))
        {
            uiName.stringValue = ((UIBindComponent) target).transform.name;
            serializedObject.ApplyModifiedProperties();
        }
    }

    public override void OnInspectorGUI()
    {
        serializedObject.Update();

        EditorGUIUtility.labelWidth = 40f;
        EditorGUILayout.PropertyField(uiName, new GUIContent("UI名称"));
        EditorGUILayout.PropertyField(uiData);

        EditorGUILayout.BeginHorizontal();
        if (GUILayout.Button("Gen Code"))
        {
            GenCode();
        }

        if (GUILayout.Button("Gen Prefab"))
        {
            GenPrefab();
        }
        EditorGUILayout.EndHorizontal();
        
        serializedObject.ApplyModifiedProperties();
    }

    private void GenCode()
    {
        var viewName = $"{uiName.stringValue}View";
        var genPath = $"{Application.dataPath}/../Codes/ModelView/Generate/UIFlow/{viewName}.cs";
        var sb = new StringBuilder();
        
        sb.AppendLine("// <AUTO-GENERATE>");
        sb.AppendLine("// This File Is Auto Generated By UIComponentEditor");
        sb.AppendLine("// </AUTO-GENERATE>");
        sb.AppendLine();
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine("using UnityEngine.UI;");
        sb.AppendLine();
        sb.AppendLine("namespace ET.UIFlow");
        sb.AppendLine("{");
        sb.AppendLine($"    public class {viewName}");
        sb.AppendLine("    {");
        sb.AppendLine("        private UIBindComponent bindComponent;");
        sb.AppendLine($"        public {viewName}(GameObject prefab)");
        sb.AppendLine("        {");
        sb.AppendLine("            this.bindComponent = prefab.GetComponent<UIBindComponent>();");
        sb.AppendLine("        }");
        sb.AppendLine();
        for (int i = 0; i < uiData.arraySize; i++)
        {
            var data = uiData.GetArrayElementAtIndex(i);
            var componentType = data.FindPropertyRelative(nameof(UIComponentData.componentType)).stringValue;
            var fieldName = data.FindPropertyRelative(nameof(UIComponentData.fieldName)).stringValue;
            sb.AppendLine($"        private {componentType} _{fieldName};");
            sb.AppendLine($"        public {componentType} {fieldName}");
            sb.AppendLine("        {");
            sb.AppendLine("            get");
            sb.AppendLine("            {");
            sb.AppendLine($"                if (this._{fieldName} == null && this.bindComponent != null)");
            sb.AppendLine($"                    this._{fieldName} = this.bindComponent.GetBindComponent<{componentType}>({i});");
            sb.AppendLine($"                return this._{fieldName};");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");

        File.WriteAllText(genPath, sb.ToString(), Encoding.UTF8);
        
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
    }

    private void GenPrefab()
    {
        var gameObject = (target as UIBindComponent).gameObject;
        if (!PrefabUtility.IsAnyPrefabInstanceRoot(gameObject) || !gameObject.name.EndsWith("_Editor"))
        {
            Debug.LogError("仅可对_Editor结尾的Prefab操作");
            return;
        }

        PrefabUtility.ApplyPrefabInstance(gameObject, InteractionMode.AutomatedAction);
        
        var runtimeName = gameObject.name.Substring(0, gameObject.name.Length - 7);
        var clone = Instantiate(gameObject);
        clone.name = runtimeName;
        
        PrefabUtility.SaveAsPrefabAsset(clone, $"{Application.dataPath}/{runtimeName}.prefab");
        DestroyImmediate(clone);
        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
    }
}